# Generated by Django 4.2.11 on 2024-11-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='recurrence_interval',
            field=models.IntegerField(blank=True, help_text='Interval in days for recurring tasks', null=True),
        ),
    ]
