# Generated by Django 4.2.11 on 2024-11-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_recurrence_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
